name: smart_park
description: smart park app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  common_utils: ^1.0.9
  fluttertoast: ^2.1.1
  image_picker: ^0.4.12
  fluro: "^1.4.0"
  json_annotation: ^2.0.0
  cached_network_image: ^0.6.2
  event_bus: ^1.0.1
  flutter_swiper: ^1.1.4

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - images/icon_login@3x.png
    - images/icon_id_card_positive@3x.png
    - images/icon_id_card_back@3x.png
    - images/icon_id_card_upload@3x.png
    - images/icon_ccecs.png
    - images/icon_choose@3x.png
    - images/icon_maintain@3x.png
    - images/icon_password@3x.png
    - images/icon_pay@3x.png
    - images/icon_service@3x.png
    - images/icon_report3x.png
    - images/ic_bluetootn_control_succeed.png
    - images/ic_bluetootn_control_error.png
    - images/ic_unbind_license_tip.png
    - images/ic_my_car.png
    - images/ic_vip_card.png